### ISSUE TITLE
How to control order of Notebooks in Table of contents

### ISSUE THREAD

**Issue by aswolf** [Notebooks-Now/submission-quarto-full#4]
Any notebooks or sub-articles (qmd files) added to the Notebooks directory automatically appear in the Notebooks section of the table of contents in the main article, **but they seem to appear in an arbitrary order**.

**How do we control the order of appearance of supplementary notebooks?**

I have tried changing notebook names by prepending numbers (e.g. 10_, 20_, 30_, etc) to the notebook file names, but this does not work. I cannot seem to find anywhere in the documentation or the quarto yml file that controls this.

Thanks!

**Comment by dragonstyle** [comment]
There isn't currently a way to control this (they may be ending up in the order that the their output would be sorted), but in any event, it should be a deterministic order minimally and maximally something you could control. I'm going to transfer this issue to the Quarto repo since that is where we'll need to fix this.

**Comment by dragonstyle** [comment]
This is actually a bit trickier to fix than I anticipated. In the meantime, you can workaround and control order explicitly in the project yaml (`_quarto.yml`) as follows:

```yaml
project:
  type: manuscript

manuscript:
  article: article.qmd
  resources:
    - data/catalogoComunSV_1663233588717.csv
    - data/lapalma_ign.csv
  code-links: [repo, devcontainer, binder]
  notebooks:
    - notebooks/visualization-figure-creation-seaborn.ipynb
    - notebooks/seismic-monitoring-stations.qmd
    - notebooks/data-screening.ipynb

...
```
